version: '3'
services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    networks: 
      - cnetwork-server

  phpmyadmin:
    container_name: admin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOSTS: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '8080:80'
    networks:
      - cnetwork-server

  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - cnetwork-server
    depends_on:
      - db

volumes:
  my-db:

networks:
  cnetwork-server:



    # app:
    # container_name: app
    # depends_on:
    #   - db
    # build: ./bezkoder-app
    # restart: unless-stopped
    # env_file: ./.env
    # ports:
    #   - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    # environment:
    #   - DB_HOST=mysqldb
    #   - DB_USER=$MYSQLDB_USER
    #   - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    #   - DB_NAME=$MYSQLDB_DATABASE
    #   - DB_PORT=$MYSQLDB_DOCKER_PORT
    # stdin_open: true
    # tty: true